name: sage
hidden_channels: 256
dropout: 0.5
batch_size: 1024
lr: 0.01
num_epoch: 5
nano_pergpu: 2
num_train_worker: 1
num_sample_worker: 1

defaults:
  - dataset: reddit
  - model: sage

root: "/data/ogb"
