params:
  reddit:
    hop: [25, 10]
    batch_size: 1024

  yelp:
    hop: [25, 10]
    batch_size: 1024

  ogbn-products:
    hop: [10, 10, 10]
    batch_size: 1024

  papers100M:
    hop: [15, 10, 5]
    batch_size: 1024
